# Tagging a commit with [circle front] will build the front page and perform test-doc.
# Tagging a commit with [circle full] will build everything.
version: 2
jobs:
    build_docs:
      docker:
        - image: cimg/python:3.9
      resource_class: medium
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV
              echo "export DISPLAY=:99" >> $BASH_ENV
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
              echo "BASH_ENV:"
              cat $BASH_ENV
        - run:
            name: Merge with upstream
            command: |
              echo $(git log -1 --pretty=%B) | tee gitlog.txt
              echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
              if [[ $(cat merge.txt) != "" ]]; then
                echo "Merging $(cat merge.txt)";
                git remote add upstream https://github.com/tgnassou/da-toolbox.git;
                git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
                git fetch upstream master;
              fi
        # Install skada environment
        - run: 
            name: Setting Up Conda skada Environment
            uses: conda-incubator/setup-miniconda@v2
            with:
              environment-file: environment.yml
              python-version: 3.7
              activate-environment: skada
              auto-activate-base: false
        - run: 
            name: Install GPU stuffs for CI
            command: |
              conda install pytorch cpuonly -y -c pytorch
        # Show Conda and Python Versions
        - run: conda --version
        - run: conda info --envs
        - run: which python

        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               which python
               python -c "import skada"
        - run:
            name: Correct link in release file
            command: |
              sed -i -r 's/PR #([[:digit:]]*)/\[PR #\1\]\(https:\/\/github.com\/tgnassou\/da-toolbox\/pull\/\1\)/' RELEASES.md
              sed -i -r 's/Issue #([[:digit:]]*)/\[Issue #\1\]\(https:\/\/github.com\/tgnassou\/da-toolbox\/issues\/\1\)/' RELEASES.md
        # Build docs
        - run:
            name: make html
            command: |
              cd docs;
              make html;
            no_output_timeout: 30m

        # Save the outputs
        - store_artifacts:
            path: docs/build/html/
            destination: dev
        - persist_to_workspace:
            root: docs/build
            paths:
              - html

    deploy_master:
      docker:
        - image: circleci/python:3.6-jessie
      steps:
        - attach_workspace:
            at: /tmp/build
        - run:
            name: Fetch docs
            command: |
              set -e
              mkdir -p ~/.ssh
              echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
              chmod og= ~/.ssh/config
              if [ ! -d ~/tgnassou.github.io ]; then
                git clone git@github.com:/tgnassou/tgnassou.github.io.git ~/tgnassou.github.io --depth=1
              fi
        - run:
            name: Deploy docs
            command: |
              set -e;
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git config --global user.email "circle@tgnassou.com";
                git config --global user.name "Circle CI";
                cd ~/tgnassou.github.io;
                git checkout master
                git remote -v
                git fetch origin
                git reset --hard origin/master
                git clean -xdf
                echo "Deploying dev docs for ${CIRCLE_BRANCH}.";
                cd master
                cp -a /tmp/build/html/* .;
                cp -a /tmp/build/html/.github/* .github/;
                touch .nojekyll;
                git add -A;
                git add -f .github/* ;
                git commit -m "CircleCI update of dev docs (${CIRCLE_BUILD_NUM}).";
                git push origin master;
              else
                echo "No deployment (build: ${CIRCLE_BRANCH}).";
              fi
    deploy_tag:
      docker:
        - image: circleci/python:3.6-jessie
      steps:
        - attach_workspace:
            at: /tmp/build
        - run:
            name: Fetch docs
            command: |
              set -e
              mkdir -p ~/.ssh
              echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
              chmod og= ~/.ssh/config
              if [ ! -d ~/tgnassou.github.io ]; then
                git clone git@github.com:/tgnassou/tgnassou.github.io.git ~/tgnassou.github.io --depth=1
              fi
        - run:
            name: Deploy docs
            command: |
              set -e;
              git config --global user.email "circle@tgnassou.com";
              git config --global user.name "Circle CI";
              cd ~/tgnassou.github.io;
              git checkout master
              git remote -v
              git fetch origin
              git reset --hard origin/master
              git clean -xdf
              echo "Deploying dev docs for ${CIRCLE_BRANCH}.";
              cp -a /tmp/build/html/* .;
              cp -a /tmp/build/html/.github/* .github/;
              touch .nojekyll;
              git add -A;
              git add -f .github/* ;
              git commit -m "CircleCI update of dev docs (${CIRCLE_BUILD_NUM}).";
              git push origin master;
workflows:
  version: 2

  default:

    jobs:
      - build_docs:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*$/
      - deploy_master:
          requires:
            - build_docs
          filters:
            branches:
              only:
                - master
      - deploy_tag:
          requires:
            - build_docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*$/