name: Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  create:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  Install-Test-skada:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:

    ## Install skada
    - name: Checking Out Repository
      uses: actions/checkout@v2
    # Cache MNE Data
    # The cache key here is fixed except for os
    # so if you download a new mne dataset in the code, best to manually increment the key below
    - name: Create/Restore MNE Data Cache
      id: cache-mne_data
      uses: actions/cache@v2
      with:
        path: ~/mne_data
        key: ${{ runner.os }}-v3
    - name: Setting Up Conda skada Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        python-version: 3.7
        activate-environment: skada
        auto-activate-base: false
    # Show Conda and Python Versions
    - run: conda --version
    - run: conda info --envs
    - run: which python
    ## Run Tests
    - name: Install Codecov etc.
      run: pip install --upgrade pytest pytest-cov codecov
    - name: Install GPU stuffs for CI
      run: conda install pytorch cpuonly -y -c pytorch
    - name: Install Skorch for CI
      run: conda install -c conda-forge skorch
    - name: Run Tests # See https://stackoverflow.com/a/59959080/1469195 for the cov-report logic
      run: pytest --cov=skada skada/ --cov-report term --cov-report xml:coverage.xml